In [4]:
cd ..

C:\Users\SAWADOGO

In [5]:
cd Desktop/OYERA/

C:\Users\SAWADOGO\Desktop\OYERA

In [100]:
import numpy as np
import pandas as pd

source ="HDR 2007-2008 Table 09_Source.xlsx"

df = pd.read_excel(source,header=2)
df.head(12)

,9 Leading global health crises and risks,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,HIV prevalencea (% aged 15-49),NaN,NaN,NaN,NaN,NaN,MDG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,MDG,NaN,NaN,NaN,Antimalarial measures,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,Condom use at last high-risk sexb\n(% aged 15-24),NaN,NaN,NaN,Use of insecticide— treated \nbednets,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,HDI rank,NaN,NaN,NaN,NaN,Women,NaN,Men,NaN,(% of children under five),...,Men,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,2006,NaN,1999-2005g,NaN,1999-2005g,NaN,1999-2005g,...,2002-04g,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1,Iceland,NaN,0.2 [0.1–0.3],NaN,..,NaN,..,NaN,..,...,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2,Norway,NaN,0.1 [0.1–0.2],NaN,..,NaN,..,NaN,..,...,27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,3,Australia,NaN,0.1 [<0.2],NaN,..,NaN,..,NaN,..,...,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,4,Canada,NaN,0.3 [0.2–0.5],NaN,..,NaN,..,NaN,..,...,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,5,Ireland,NaN,0.2 [0.1–0.4],NaN,..,NaN,..,NaN,..,...,28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [101]:
# https://stackoverflow.com/a/51794989
# Supprimez d'abord toutes les colonnes (axe=1) sans valeurs
df = df.dropna(how="all", axis=1)
# Supprimer toutes les lignes (axe=0) sans valeurs
df = df.dropna(how="all", axis=0).reset_index(drop=True)
df.head(6)

,9 Leading global health crises and risks,Unnamed: 1,Unnamed: 3,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
0,NaN,NaN,HIV prevalencea (% aged 15-49),NaN,NaN,NaN,NaN,MDG,NaN,MDG,MDG,NaN,MDG,NaN,MDG,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,MDG,NaN,NaN,NaN,Antimalarial measures,NaN,NaN,Tuberculosis cases,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,Condom use at last high-risk sexb\n(% aged 15-24),NaN,NaN,NaN,Use of insecticide— treated \nbednets,NaN,Fevers treated with \nantimalarial drugs,"Prevalencec \n(per 100,000 people)",NaN,Detected under DOTSd\n(%),NaN,Cured under DOTSe\n(%),NaN,Prevalence of smoking\n(% of adults)f,NaN,NaN,NaN
3,HDI rank,NaN,NaN,Women,NaN,Men,NaN,(% of children under five),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Women,NaN,Men,NaN
4,NaN,NaN,2006,1999-2005g,NaN,1999-2005g,NaN,1999-2005g,NaN,1999-2005g,2005,NaN,2005,NaN,2004,NaN,2002-04g,NaN,2002-04g,NaN
5,HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [102]:
columns = []
for c in df.columns:
    # Pour chaque colonne, obtenir les valeurs des 5 premières lignes
    # puis conservez toutes les chaînes (c'est-à-dire excluez-les si elles sont nulles) et ajoutez-les en colonne
    columns.append([str(v) for v in df[c][:5] if pd.notnull(v)])
columns

[['HDI rank'],
 [],
 ['HIV prevalencea (% aged 15-49)', '2006'],
 ['MDG',
  'Condom use at last high-risk sexb\n(% aged 15-24)',
  'Women',
  '1999-2005g'],
 [],
 ['Men', '1999-2005g'],
 [],
 ['MDG',
  'Antimalarial measures',
  'Use of insecticide— treated \nbednets',
  '(% of children under five)',
  '1999-2005g'],
 [],
 ['MDG', 'Fevers treated with \nantimalarial drugs', '1999-2005g'],
 ['MDG', 'Tuberculosis cases', 'Prevalencec \n(per 100,000 people)', '2005'],
 [],
 ['MDG', 'Detected under DOTSd\n(%)', '2005'],
 [],
 ['MDG', 'Cured under DOTSe\n(%)', '2004'],
 [],
 ['Prevalence of smoking\n(% of adults)f', 'Women', '2002-04g'],
 [],
 ['Men', '2002-04g'],
 []]

In [103]:
columns=["HDI rank",
         "Country",
         "HIV prevalencea (% aged 15-49) 2006",
        "Condom use at last high-risk sex(% aged 15-24) Women 1999-2005",
        "Reference 1",
         "Condom use at last high-risk sex(% aged 15-24) Men 1999-2005",
        "Reference 2",
        "Antimalarial measures-Use of insecticide— treated bednets (% of children under five) 1999-2005",
        "Reference 3",
        "Antimalarial measures-Fevers treated with antimalarial drugs 1999-2005",
        "Tuberculosis cases Prevalence (per 100,000 people) 2005",
        "Reference 4",
        "Tuberculosis cases Detected under DOTS(%) 2005",
        "Reference 5",
        "Tuberculosis cases Cured under DOTS(%) 2004",
        "Reference 6",
        "Prevalence of smoking(% of adults) Women 2002-04",
        "Reference 7",
        "Prevalence of smoking(% of adults) Men 2002-04",
        "Reference 8"]

In [104]:
# Réinitialiser les colonnes des cadres de données
df.columns = columns
# Supprimer les lignes qui contenaient les informations dont nous n'avons plus besoin
# et réinitialiser l'index
# np.arange(5) crée un tableau = [0, 1, 2, 3, 4, 5]
df = df.drop(np.arange(5), axis=0).reset_index(drop=True)
df.head()

,HDI rank,Country,HIV prevalencea (% aged 15-49) 2006,Condom use at last high-risk sex(% aged 15-24) Women 1999-2005,Reference 1,Condom use at last high-risk sex(% aged 15-24) Men 1999-2005,Reference 2,Antimalarial measures-Use of insecticide— treated bednets (% of children under five) 1999-2005,Reference 3,Antimalarial measures-Fevers treated with antimalarial drugs 1999-2005,"Tuberculosis cases Prevalence (per 100,000 people) 2005",Reference 4,Tuberculosis cases Detected under DOTS(%) 2005,Reference 5,Tuberculosis cases Cured under DOTS(%) 2004,Reference 6,Prevalence of smoking(% of adults) Women 2002-04,Reference 7,Prevalence of smoking(% of adults) Men 2002-04,Reference 8
0,HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Iceland,0.2 [0.1–0.3],..,NaN,..,NaN,..,NaN,..,2,NaN,53,NaN,50,NaN,20,NaN,25,NaN
2,2,Norway,0.1 [0.1–0.2],..,NaN,..,NaN,..,NaN,..,4,NaN,44,NaN,89,NaN,25,NaN,27,NaN
3,3,Australia,0.1 [<0.2],..,NaN,..,NaN,..,NaN,..,6,NaN,42,NaN,85,NaN,16,NaN,19,NaN
4,4,Canada,0.3 [0.2–0.5],..,NaN,..,NaN,..,NaN,..,4,NaN,64,NaN,62,NaN,17,NaN,22,NaN

In [105]:
df.tail(30)

,HDI rank,Country,HIV prevalencea (% aged 15-49) 2006,Condom use at last high-risk sex(% aged 15-24) Women 1999-2005,Reference 1,Condom use at last high-risk sex(% aged 15-24) Men 1999-2005,Reference 2,Antimalarial measures-Use of insecticide— treated bednets (% of children under five) 1999-2005,Reference 3,Antimalarial measures-Fevers treated with antimalarial drugs 1999-2005,"Tuberculosis cases Prevalence (per 100,000 people) 2005",Reference 4,Tuberculosis cases Detected under DOTS(%) 2005,Reference 5,Tuberculosis cases Cured under DOTS(%) 2004,Reference 6,Prevalence of smoking(% of adults) Women 2002-04,Reference 7,Prevalence of smoking(% of adults) Men 2002-04,Reference 8
153,152,Togo,3.2 [1.9–4.7],22,j,54,j,54,NaN,60,753,NaN,18,NaN,67,NaN,..,NaN,..,NaN
154,153,Yemen,[<0.2],..,NaN,..,NaN,..,NaN,..,136,NaN,41,NaN,82,NaN,..,NaN,..,NaN
155,154,Uganda,6.7 [5.7–7.6],53,NaN,55,NaN,0,NaN,..,559,NaN,45,NaN,70,NaN,3,h,25,h
156,155,Gambia,2.4 [1.2–4.1],..,NaN,..,NaN,15,NaN,55,352,NaN,69,NaN,86,NaN,..,NaN,..,NaN
157,LOW HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158,156,Senegal,0.9 [0.4–1.5],36,NaN,52,NaN,14,NaN,29,466,NaN,51,NaN,74,NaN,..,NaN,..,NaN
159,157,Eritrea,2.4 [1.3–3.9],..,NaN,..,NaN,4,NaN,4,515,NaN,13,NaN,85,NaN,..,NaN,..,NaN
160,158,Nigeria,3.9 [2.3–5.6],24,NaN,46,NaN,1,NaN,34,536,NaN,22,NaN,73,NaN,1,NaN,..,NaN
161,159,Tanzania (United Republic of),6.5 [5.8–7.2],42,NaN,47,NaN,16,NaN,58,496,NaN,45,NaN,81,NaN,..,NaN,..,NaN
162,160,Guinea,1.5 [1.2–1.8],17,NaN,32,NaN,4,NaN,56,431,NaN,56,NaN,72,NaN,..,NaN,..,NaN
163,161,Rwanda,3.1 [2.9–3.2],26,NaN,40,NaN,5,NaN,13,673,NaN,29,NaN,77,NaN,..,NaN,..,NaN
164,162,Angola,3.7 [2.3–5.3],..,NaN,..,NaN,2,NaN,63,333,NaN,85,NaN,68,NaN,..,NaN,..,NaN
165,163,Benin,1.8 [1.2–2.5],19,NaN,34,NaN,7,NaN,60,144,NaN,83,NaN,83,NaN,..,NaN,..,NaN
166,164,Malawi,14.1 [6.9–21.4],35,NaN,47,NaN,15,NaN,28,518,NaN,39,NaN,71,NaN,5,NaN,21,NaN
167,165,Zambia,17 [15.9–18.1],35,NaN,40,NaN,7,NaN,52,618,NaN,52,NaN,83,NaN,1,NaN,16,NaN
168,166,Côte d'Ivoire,7.1 [4.3–9.7],25,j,56,j,4,NaN,58,659,NaN,38,NaN,71,NaN,..,NaN,..,NaN
169,167,Burundi,3.3 [2.7–3.8],..,NaN,..,NaN,1,NaN,31,602,NaN,30,NaN,78,NaN,..,NaN,..,NaN
170,168,Congo (Democratic Republic of the),3.2 [1.8–4.9],..,NaN,..,NaN,1,NaN,45,541,NaN,72,NaN,85,NaN,..,NaN,..,NaN
171,169,Ethiopia,[0.9–3.5],17,NaN,30,NaN,1,NaN,3,546,NaN,33,NaN,79,NaN,(.),NaN,6,NaN
172,170,Chad,3.5 [1.7–6.0],17,NaN,25,NaN,1,j,44,495,NaN,22,NaN,69,NaN,..,NaN,..,NaN
173,171,Central African Republic,10.7 [4.5–17.2],..,NaN,..,NaN,2,NaN,69,483,NaN,40,NaN,91,NaN,..,NaN,..,NaN
174,172,Mozambique,16.1 [12.5–20.0],29,NaN,33,NaN,..,NaN,15,597,NaN,49,NaN,77,NaN,..,NaN,..,NaN
175,173,Mali,1.7 [1.3–2.1],14,NaN,30,NaN,8,NaN,38,578,NaN,21,NaN,71,NaN,..,NaN,..,NaN
176,174,Niger,1.1 [0.5–1.9],7,j,30,j,6,NaN,48,294,NaN,50,NaN,61,NaN,..,NaN,..,NaN
177,175,Guinea-Bissau,3.8 [2.1–6.0],..,NaN,..,NaN,7,NaN,58,293,NaN,79,NaN,75,NaN,..,NaN,..,NaN
178,176,Burkina Faso,2 [1.5–2.5],54,NaN,67,NaN,2,NaN,50,461,NaN,18,NaN,67,NaN,..,NaN,..,NaN
179,177,Sierra Leone,1.6 [0.9–2.4],..,NaN,..,NaN,2,NaN,61,905,NaN,37,NaN,82,NaN,..,NaN,..,NaN
180,NOTES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
181,a. Data are point and range estimates based on...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182,SOURCES\nColumn 1: UNAIDS 2006.\nColumns 2–5: ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [106]:
# Déposer les lignes du bas des données que nous voulons conserver, jusqu'à la fin (défini comme len(df))
df = df.drop(np.arange(180,len(df)), axis=0).reset_index(drop=True)

In [107]:
df.tail()

,HDI rank,Country,HIV prevalencea (% aged 15-49) 2006,Condom use at last high-risk sex(% aged 15-24) Women 1999-2005,Reference 1,Condom use at last high-risk sex(% aged 15-24) Men 1999-2005,Reference 2,Antimalarial measures-Use of insecticide— treated bednets (% of children under five) 1999-2005,Reference 3,Antimalarial measures-Fevers treated with antimalarial drugs 1999-2005,"Tuberculosis cases Prevalence (per 100,000 people) 2005",Reference 4,Tuberculosis cases Detected under DOTS(%) 2005,Reference 5,Tuberculosis cases Cured under DOTS(%) 2004,Reference 6,Prevalence of smoking(% of adults) Women 2002-04,Reference 7,Prevalence of smoking(% of adults) Men 2002-04,Reference 8
175,173,Mali,1.7 [1.3–2.1],14,NaN,30,NaN,8,NaN,38,578,NaN,21,NaN,71,NaN,..,NaN,..,NaN
176,174,Niger,1.1 [0.5–1.9],7,j,30,j,6,NaN,48,294,NaN,50,NaN,61,NaN,..,NaN,..,NaN
177,175,Guinea-Bissau,3.8 [2.1–6.0],..,NaN,..,NaN,7,NaN,58,293,NaN,79,NaN,75,NaN,..,NaN,..,NaN
178,176,Burkina Faso,2 [1.5–2.5],54,NaN,67,NaN,2,NaN,50,461,NaN,18,NaN,67,NaN,..,NaN,..,NaN
179,177,Sierra Leone,1.6 [0.9–2.4],..,NaN,..,NaN,2,NaN,61,905,NaN,37,NaN,82,NaN,..,NaN,..,NaN

In [108]:

hdi_categories = ["HIGH HUMAN DEVELOPMENT", "MEDIUM HUMAN DEVELOPMENT", "LOW HUMAN DEVELOPMENT"]
# Se débarrasser des rangées avec les catégories HDI
# https://stackoverflow.com/a/27360130 & https://stackoverflow.com/a/12098586
df = df.drop(df[df["HDI rank"].isin(hdi_categories)].index, axis=0).reset_index(drop=True)
# Référence pour np.where https://docs.scipy.org/doc/numpy/reference/generated/numpy.where.html
# Pensez que cela ressemble à une déclaration du type "if" : where(test est vrai, vrai-quelque chose, faux-quelque chose)
# ceci peut aussi être imbriqué : where(test is true, true-thing, where(new-test is true, true-thing, false-thing))
df.loc[:, "HDI category"] = np.where(df["HDI rank"] >155,
                                     "LOW HUMAN DEVELOPMENT",
                                     np.where(df["HDI rank"] > 70,
                                              "MEDIUM HUMAN DEVELOPMENT",
                                              "HIGH HUMAN DEVELOPMENT"
                                             )
                                    )
df.sort_values(by="HDI rank", inplace=True)
df.head()

,HDI rank,Country,HIV prevalencea (% aged 15-49) 2006,Condom use at last high-risk sex(% aged 15-24) Women 1999-2005,Reference 1,Condom use at last high-risk sex(% aged 15-24) Men 1999-2005,Reference 2,Antimalarial measures-Use of insecticide— treated bednets (% of children under five) 1999-2005,Reference 3,Antimalarial measures-Fevers treated with antimalarial drugs 1999-2005,...,Reference 4,Tuberculosis cases Detected under DOTS(%) 2005,Reference 5,Tuberculosis cases Cured under DOTS(%) 2004,Reference 6,Prevalence of smoking(% of adults) Women 2002-04,Reference 7,Prevalence of smoking(% of adults) Men 2002-04,Reference 8,HDI category
0,1,Iceland,0.2 [0.1–0.3],..,NaN,..,NaN,..,NaN,..,...,NaN,53,NaN,50,NaN,20,NaN,25,NaN,HIGH HUMAN DEVELOPMENT
1,2,Norway,0.1 [0.1–0.2],..,NaN,..,NaN,..,NaN,..,...,NaN,44,NaN,89,NaN,25,NaN,27,NaN,HIGH HUMAN DEVELOPMENT
2,3,Australia,0.1 [<0.2],..,NaN,..,NaN,..,NaN,..,...,NaN,42,NaN,85,NaN,16,NaN,19,NaN,HIGH HUMAN DEVELOPMENT
3,4,Canada,0.3 [0.2–0.5],..,NaN,..,NaN,..,NaN,..,...,NaN,64,NaN,62,NaN,17,NaN,22,NaN,HIGH HUMAN DEVELOPMENT
4,5,Ireland,0.2 [0.1–0.4],..,NaN,..,NaN,..,NaN,..,...,NaN,0,NaN,..,NaN,26,NaN,28,NaN,HIGH HUMAN DEVELOPMENT

In [91]:
df.head()

,HDI rank,Country,HIV prevalencea (% aged 15-49) 2006,Condom use at last high-risk sex(% aged 15-24) Women 1999-2005,Reference 1,Condom use at last high-risk sex(% aged 15-24) Men 1999-2005,Reference 2,Antimalarial measures-Use of insecticide— treated bednets (% of children under five) 1999-2005,Reference 3,Antimalarial measures-Fevers treated with antimalarial drugs 1999-2005,...,Reference 4,Tuberculosis cases Detected under DOTS(%) 2005,Reference 5,Tuberculosis cases Cured under DOTS(%) 2004,Reference 6,Prevalence of smoking(% of adults) Women 2002-04,Reference 7,Prevalence of smoking(% of adults) Men 2002-04,Reference 8,HDI category
0,1,Iceland,0.2 [0.1–0.3],..,NaN,..,NaN,..,NaN,..,...,NaN,53,NaN,50,NaN,20,NaN,25,NaN,HIGH HUMAN DEVELOPMENT
1,2,Norway,0.1 [0.1–0.2],..,NaN,..,NaN,..,NaN,..,...,NaN,44,NaN,89,NaN,25,NaN,27,NaN,HIGH HUMAN DEVELOPMENT
2,3,Australia,0.1 [<0.2],..,NaN,..,NaN,..,NaN,..,...,NaN,42,NaN,85,NaN,16,NaN,19,NaN,HIGH HUMAN DEVELOPMENT
3,4,Canada,0.3 [0.2–0.5],..,NaN,..,NaN,..,NaN,..,...,NaN,64,NaN,62,NaN,17,NaN,22,NaN,HIGH HUMAN DEVELOPMENT
4,5,Ireland,0.2 [0.1–0.4],..,NaN,..,NaN,..,NaN,..,...,NaN,0,NaN,..,NaN,26,NaN,28,NaN,HIGH HUMAN DEVELOPMENT

In [109]:
#séparation des amplitudes et des intervalles dans respectivement C1 et C1
A= []
C1=[]
C2=[]
for i in df.iloc[:,2]:
        A.append(i.split(" "))
for j in A:
    C1.append(j[0])
    C2.append(j[-1])

In [110]:
C1

['0.2',
 '0.1',
 '0.1',
 '0.3',
 '0.2',
 '0.2',
 '0.4',
 '<0.1',
 '0.2',
 '0.4',
 '0.1',
 '0.6',
 '0.6',
 '0.2',
 '0.3',
 '0.2',
 '0.3',
 '0.2',
 '0.1',
 '0.5',
 '..',
 '0.1',
 '',
 '0.2',
 '0.3',
 '<0.1',
 '<0.1',
 '',
 '0.4',
 '<0.1',
 '1.5',
 '0.1',
 '',
 '0.1',
 '',
 '0.1',
 '0.1',
 '0.6',
 '',
 '0.3',
 '',
 '<0.1',
 '0.2',
 '1.3',
 '0.8',
 '0.5',
 '<0.1',
 '0.3',
 '3.3',
 '..',
 '0.1',
 '0.3',
 '<0.1',
 '..',
 '..',
 '',
 '..',
 '',
 '2.6',
 '<0.1',
 '',
 '0.9',
 '0.5',
 '0.3',
 '0.6',
 '<0.1',
 '1.1',
 '',
 '<0.1',
 '0.5',
 '..',
 '..',
 '0.1',
 '0.7',
 '0.6',
 '1.4',
 '..',
 '1.4',
 '1.1',
 '2.5',
 '0.1',
 '..',
 '0.1',
 '',
 '1.9',
 '',
 '0.6',
 '0.1',
 '0.3',
 '<0.1',
 '0.1',
 '0.1',
 '..',
 '0.2',
 '0.4',
 '0.2',
 '2.4',
 '0.1',
 '<0.1',
 '',
 '1.5',
 '..',
 '0.9',
 '0.1',
 '0.5',
 '..',
 '0.1',
 '',
 '<0.1',
 '0.2',
 '1.1',
 '<0.1',
 '0.2',
 '<0.1',
 '1.5',
 '0.1',
 '0.1',
 '0.9',
 '7.9',
 '..',
 '18.8',
 '0.1',
 '..',
 '24.1',
 '19.6',
 '0.1',
 '3.2',
 '0.9',
 '..',
 '0.1',
 '1.6',
 '1.3',
 '<0.1',
 '<0.1',
 '2.3',
 '0.1',
 '0.7',
 '23.2',
 '5.3',
 '<0.1',
 '33.4',
 '0.5',
 '0.5',
 '5.4',
 '1.8',
 '3.8',
 '1.6',
 '6.1',
 '3.1',
 '',
 '20.1',
 '3.2',
 '',
 '6.7',
 '2.4',
 '0.9',
 '2.4',
 '3.9',
 '6.5',
 '1.5',
 '3.1',
 '3.7',
 '1.8',
 '14.1',
 '17',
 '7.1',
 '3.3',
 '3.2',
 '',
 '3.5',
 '10.7',
 '16.1',
 '1.7',
 '1.1',
 '3.8',
 '2',
 '1.6']

In [111]:
C2

['[0.1–0.3]',
 '[0.1–0.2]',
 '[<0.2]',
 '[0.2–0.5]',
 '[0.1–0.4]',
 '[0.1–0.3]',
 '[0.3–0.8]',
 '[<0.2]',
 '[0.1–0.4]',
 '[0.3–0.8]',
 '[<0.2]',
 '[0.4–1.0]',
 '[0.4–1.0]',
 '[0.1–0.4]',
 '[0.2–0.5]',
 '[0.1–0.4]',
 '[0.2–0.5]',
 '[0.1–0.4]',
 '[<0.2]',
 '[0.3–0.9]',
 '',
 '[0.1–0.2]',
 '[<0.2]',
 '[0.1–0.3]',
 '[0.2–0.7]',
 '[<0.2]',
 '[<0.2]',
 '[<0.2]',
 '[0.3–0.9]',
 '[<0.2]',
 '[0.8–2.5]',
 '[<0.2]',
 '[<0.2]',
 '[0.1–0.2]',
 '[<0.2]',
 '[<0.2]',
 '[0.1–0.2]',
 '[0.3–1.9]',
 '[<0.2]',
 '[0.2–1.2]',
 '[<0.2]',
 '[<0.2]',
 '[0.1–0.6]',
 '[0.6–4.3]',
 '[0.5–1.3]',
 '[0.2–6.1]',
 '[<0.2]',
 '[0.1–3.6]',
 '[1.3–4.5]',
 '',
 '[<0.2]',
 '[0.2–0.7]',
 '[<0.2]',
 '',
 '',
 '[<0.2]',
 '',
 '[<0.2]',
 '[1.4–4.2]',
 '[<0.2]',
 '[<0.2]',
 '[0.5–3.7]',
 '[0.2–1.5]',
 '[0.2–0.8]',
 '[0.3–1.8]',
 '[<0.2]',
 '[0.7–1.8]',
 '[<0.2]',
 '[<0.2]',
 '[0.3–1.6]',
 '',
 '',
 '[0.1–3.2]',
 '[0.3–8.9]',
 '[0.3–2.5]',
 '[0.8–4.3]',
 '',
 '[0.7–2.1]',
 '[0.9–1.3]',
 '[1.4–4.0]',
 '[<0.2]',
 '',
 '[0.1–0.6]',
 '[<0.2]',
 '[1.1–3.1]',
 '[<0.2]',
 '[0.3–1.7]',
 '[0.1–0.5]',
 '[0.1–3.5]',
 '[<0.2]',
 '[0.1–0.3]',
 '[0.1–0.4]',
 '',
 '[0.1–0.4]',
 '[0.2–4.6]',
 '[0.1–2.7]',
 '[1.0–4.9]',
 '[0.1–0.4]',
 '[<0.2]',
 '[<0.2]',
 '[0.8–2.4]',
 '',
 '[0.5–3.8]',
 '[<0.2]',
 '[0.3–0.9]',
 '',
 '[0.1–0.2]',
 '[<0.2]',
 '[<0.2]',
 '[0.1–0.6]',
 '[0.6–2.6]',
 '[<0.2]',
 '[0.1–0.7]',
 '[<0.2]',
 '[0.8–2.4]',
 '[0.1–1.7]',
 '[0.1–0.3]',
 '[0.5–2.7]',
 '[5.1–11.5]',
 '',
 '[16.8–20.7]',
 '[0.1–1.7]',
 '',
 '[23.0–32.0]',
 '[8.6–31.7]',
 '[0.1–0.4]',
 '[2.6–3.8]',
 '[0.5–1.5]',
 '',
 '[0.1–0.4]',
 '[0.9–2.6]',
 '[0.7–2.0]',
 '[<0.2]',
 '[<0.2]',
 '[1.9–2.6]',
 '[0.1–0.2]',
 '[0.4–2.8]',
 '[21.9–24.7]',
 '[3.3–7.5]',
 '[<0.2]',
 '[21.2–45.3]',
 '[0.3–1.3]',
 '[0.2–1.2]',
 '[4.9–5.9]',
 '[0.9–4.4]',
 '[2.2–5.4]',
 '[0.8–2.7]',
 '[5.2–7.0]',
 '[0.8–6.9]',
 '[<0.2]',
 '[13.3–27.6]',
 '[1.9–4.7]',
 '[<0.2]',
 '[5.7–7.6]',
 '[1.2–4.1]',
 '[0.4–1.5]',
 '[1.3–3.9]',
 '[2.3–5.6]',
 '[5.8–7.2]',
 '[1.2–1.8]',
 '[2.9–3.2]',
 '[2.3–5.3]',
 '[1.2–2.5]',
 '[6.9–21.4]',
 '[15.9–18.1]',
 '[4.3–9.7]',
 '[2.7–3.8]',
 '[1.8–4.9]',
 '[0.9–3.5]',
 '[1.7–6.0]',
 '[4.5–17.2]',
 '[12.5–20.0]',
 '[1.3–2.1]',
 '[0.5–1.9]',
 '[2.1–6.0]',
 '[1.5–2.5]',
 '[0.9–2.4]']

In [112]:
#Supression de la colone 2
df = df.drop(df.columns[2],axis=1)
#insertion des amplitudes et des fourchette d'estimation comme colone de notre dataframe
df.loc[:,"HIV prevalencea (% aged 15-49) 2006 range estimate"]=C2
df.loc[:,"HIV prevalencea (% aged 15-49) 2006 magnitude of the estimation interval"]=C1

In [113]:
df

,HDI rank,Country,Condom use at last high-risk sex(% aged 15-24) Women 1999-2005,Reference 1,Condom use at last high-risk sex(% aged 15-24) Men 1999-2005,Reference 2,Antimalarial measures-Use of insecticide— treated bednets (% of children under five) 1999-2005,Reference 3,Antimalarial measures-Fevers treated with antimalarial drugs 1999-2005,"Tuberculosis cases Prevalence (per 100,000 people) 2005",...,Reference 5,Tuberculosis cases Cured under DOTS(%) 2004,Reference 6,Prevalence of smoking(% of adults) Women 2002-04,Reference 7,Prevalence of smoking(% of adults) Men 2002-04,Reference 8,HDI category,HIV prevalencea (% aged 15-49) 2006 range estimate,HIV prevalencea (% aged 15-49) 2006 magnitude of the estimation interval
0,1,Iceland,..,NaN,..,NaN,..,NaN,..,2,...,NaN,50,NaN,20,NaN,25,NaN,HIGH HUMAN DEVELOPMENT,[0.1–0.3],0.2
1,2,Norway,..,NaN,..,NaN,..,NaN,..,4,...,NaN,89,NaN,25,NaN,27,NaN,HIGH HUMAN DEVELOPMENT,[0.1–0.2],0.1
2,3,Australia,..,NaN,..,NaN,..,NaN,..,6,...,NaN,85,NaN,16,NaN,19,NaN,HIGH HUMAN DEVELOPMENT,[<0.2],0.1
3,4,Canada,..,NaN,..,NaN,..,NaN,..,4,...,NaN,62,NaN,17,NaN,22,NaN,HIGH HUMAN DEVELOPMENT,[0.2–0.5],0.3
4,5,Ireland,..,NaN,..,NaN,..,NaN,..,10,...,NaN,..,NaN,26,NaN,28,NaN,HIGH HUMAN DEVELOPMENT,[0.1–0.4],0.2
5,6,Sweden,..,NaN,..,NaN,..,NaN,..,5,...,NaN,64,NaN,18,NaN,17,NaN,HIGH HUMAN DEVELOPMENT,[0.1–0.3],0.2
6,7,Switzerland,..,NaN,..,NaN,..,NaN,..,6,...,NaN,..,NaN,23,NaN,27,NaN,HIGH HUMAN DEVELOPMENT,[0.3–0.8],0.4
7,8,Japan,..,NaN,..,NaN,..,NaN,..,38,...,NaN,57,NaN,15,NaN,47,NaN,HIGH HUMAN DEVELOPMENT,[<0.2],<0.1
8,9,Netherlands,..,NaN,..,NaN,..,NaN,..,5,...,NaN,83,NaN,28,NaN,36,NaN,HIGH HUMAN DEVELOPMENT,[0.1–0.4],0.2
9,10,France,..,NaN,..,NaN,..,NaN,..,10,...,h,..,NaN,21,NaN,30,NaN,HIGH HUMAN DEVELOPMENT,[0.3–0.8],0.4
10,11,Finland,..,NaN,..,NaN,..,NaN,..,5,...,h,..,NaN,19,NaN,26,NaN,HIGH HUMAN DEVELOPMENT,[<0.2],0.1
11,12,United States,..,NaN,..,NaN,..,NaN,..,3,...,NaN,61,NaN,19,NaN,24,NaN,HIGH HUMAN DEVELOPMENT,[0.4–1.0],0.6
12,13,Spain,..,NaN,..,NaN,..,NaN,..,22,...,NaN,..,NaN,25,h,39,h,HIGH HUMAN DEVELOPMENT,[0.4–1.0],0.6
13,14,Denmark,..,NaN,..,NaN,..,NaN,..,6,...,NaN,88,NaN,25,NaN,31,NaN,HIGH HUMAN DEVELOPMENT,[0.1–0.4],0.2
14,15,Austria,..,NaN,..,NaN,..,NaN,..,9,...,NaN,69,NaN,..,NaN,..,NaN,HIGH HUMAN DEVELOPMENT,[0.2–0.5],0.3
15,16,United Kingdom,..,NaN,..,NaN,..,NaN,..,11,...,NaN,..,NaN,25,NaN,27,NaN,HIGH HUMAN DEVELOPMENT,[0.1–0.4],0.2
16,17,Belgium,..,NaN,..,NaN,..,NaN,..,10,...,NaN,72,NaN,25,NaN,30,NaN,HIGH HUMAN DEVELOPMENT,[0.2–0.5],0.3
17,18,Luxembourg,..,NaN,..,NaN,..,NaN,..,9,...,NaN,..,NaN,26,NaN,39,NaN,HIGH HUMAN DEVELOPMENT,[0.1–0.4],0.2
18,19,New Zealand,..,NaN,..,NaN,..,NaN,..,9,...,NaN,66,NaN,22,NaN,24,NaN,HIGH HUMAN DEVELOPMENT,[<0.2],0.1
19,20,Italy,..,NaN,..,NaN,..,NaN,..,5,...,NaN,95,h,17,NaN,31,NaN,HIGH HUMAN DEVELOPMENT,[0.3–0.9],0.5
20,21,"Hong Kong, China (SAR)",..,NaN,..,NaN,..,NaN,..,77,...,"h,i",78,"h,i",4,h,22,h,HIGH HUMAN DEVELOPMENT,,..
21,22,Germany,..,NaN,..,NaN,..,NaN,..,6,...,NaN,68,NaN,28,NaN,37,NaN,HIGH HUMAN DEVELOPMENT,[0.1–0.2],0.1
22,23,Israel,..,NaN,..,NaN,..,NaN,..,6,...,NaN,80,NaN,18,NaN,32,NaN,HIGH HUMAN DEVELOPMENT,[<0.2],
23,24,Greece,..,NaN,..,NaN,..,NaN,..,15,...,NaN,..,NaN,29,h,47,h,HIGH HUMAN DEVELOPMENT,[0.1–0.3],0.2
24,25,Singapore,..,NaN,..,NaN,..,NaN,..,28,...,NaN,81,NaN,4,h,24,h,HIGH HUMAN DEVELOPMENT,[0.2–0.7],0.3
25,26,Korea (Republic of),..,NaN,..,NaN,..,NaN,..,135,...,NaN,80,NaN,..,NaN,..,NaN,HIGH HUMAN DEVELOPMENT,[<0.2],<0.1
26,27,Slovenia,..,NaN,..,NaN,..,NaN,..,15,...,NaN,90,NaN,20,h,28,h,HIGH HUMAN DEVELOPMENT,[<0.2],<0.1
27,28,Cyprus,..,NaN,..,NaN,..,NaN,..,5,...,NaN,20,NaN,..,NaN,..,NaN,HIGH HUMAN DEVELOPMENT,[<0.2],
28,29,Portugal,..,NaN,..,NaN,..,NaN,..,25,...,NaN,84,NaN,..,NaN,..,NaN,HIGH HUMAN DEVELOPMENT,[0.3–0.9],0.4
29,30,Brunei Darussalam,..,NaN,..,NaN,..,NaN,..,63,...,NaN,71,NaN,..,NaN,..,NaN,HIGH HUMAN DEVELOPMENT,[<0.2],<0.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147,148,Kenya,25,NaN,47,NaN,5,NaN,27,936,...,NaN,80,NaN,1,NaN,21,NaN,MEDIUM HUMAN DEVELOPMENT,[5.2–7.0],6.1
148,149,Djibouti,..,NaN,..,NaN,..,NaN,..,"1,161",...,NaN,80,NaN,..,NaN,..,NaN,MEDIUM HUMAN DEVELOPMENT,[0.8–6.9],3.1
149,150,Timor-Leste,..,NaN,..,NaN,8,j,19,713,...,NaN,80,NaN,..,NaN,..,NaN,MEDIUM HUMAN DEVELOPMENT,[<0.2],
150,151,Zimbabwe,42,NaN,69,NaN,..,NaN,..,631,...,NaN,54,NaN,2,NaN,20,NaN,MEDIUM HUMAN DEVELOPMENT,[13.3–27.6],20.1
151,152,Togo,22,j,54,j,54,NaN,60,753,...,NaN,67,NaN,..,NaN,..,NaN,MEDIUM HUMAN DEVELOPMENT,[1.9–4.7],3.2
152,153,Yemen,..,NaN,..,NaN,..,NaN,..,136,...,NaN,82,NaN,..,NaN,..,NaN,MEDIUM HUMAN DEVELOPMENT,[<0.2],
153,154,Uganda,53,NaN,55,NaN,0,NaN,..,559,...,NaN,70,NaN,3,h,25,h,MEDIUM HUMAN DEVELOPMENT,[5.7–7.6],6.7
154,155,Gambia,..,NaN,..,NaN,15,NaN,55,352,...,NaN,86,NaN,..,NaN,..,NaN,MEDIUM HUMAN DEVELOPMENT,[1.2–4.1],2.4
155,156,Senegal,36,NaN,52,NaN,14,NaN,29,466,...,NaN,74,NaN,..,NaN,..,NaN,LOW HUMAN DEVELOPMENT,[0.4–1.5],0.9
156,157,Eritrea,..,NaN,..,NaN,4,NaN,4,515,...,NaN,85,NaN,..,NaN,..,NaN,LOW HUMAN DEVELOPMENT,[1.3–3.9],2.4
157,158,Nigeria,24,NaN,46,NaN,1,NaN,34,536,...,NaN,73,NaN,1,NaN,..,NaN,LOW HUMAN DEVELOPMENT,[2.3–5.6],3.9
158,159,Tanzania (United Republic of),42,NaN,47,NaN,16,NaN,58,496,...,NaN,81,NaN,..,NaN,..,NaN,LOW HUMAN DEVELOPMENT,[5.8–7.2],6.5
159,160,Guinea,17,NaN,32,NaN,4,NaN,56,431,...,NaN,72,NaN,..,NaN,..,NaN,LOW HUMAN DEVELOPMENT,[1.2–1.8],1.5
160,161,Rwanda,26,NaN,40,NaN,5,NaN,13,673,...,NaN,77,NaN,..,NaN,..,NaN,LOW HUMAN DEVELOPMENT,[2.9–3.2],3.1
161,162,Angola,..,NaN,..,NaN,2,NaN,63,333,...,NaN,68,NaN,..,NaN,..,NaN,LOW HUMAN DEVELOPMENT,[2.3–5.3],3.7
162,163,Benin,19,NaN,34,NaN,7,NaN,60,144,...,NaN,83,NaN,..,NaN,..,NaN,LOW HUMAN DEVELOPMENT,[1.2–2.5],1.8
163,164,Malawi,35,NaN,47,NaN,15,NaN,28,518,...,NaN,71,NaN,5,NaN,21,NaN,LOW HUMAN DEVELOPMENT,[6.9–21.4],14.1
164,165,Zambia,35,NaN,40,NaN,7,NaN,52,618,...,NaN,83,NaN,1,NaN,16,NaN,LOW HUMAN DEVELOPMENT,[15.9–18.1],17
165,166,Côte d'Ivoire,25,j,56,j,4,NaN,58,659,...,NaN,71,NaN,..,NaN,..,NaN,LOW HUMAN DEVELOPMENT,[4.3–9.7],7.1
166,167,Burundi,..,NaN,..,NaN,1,NaN,31,602,...,NaN,78,NaN,..,NaN,..,NaN,LOW HUMAN DEVELOPMENT,[2.7–3.8],3.3
167,168,Congo (Democratic Republic of the),..,NaN,..,NaN,1,NaN,45,541,...,NaN,85,NaN,..,NaN,..,NaN,LOW HUMAN DEVELOPMENT,[1.8–4.9],3.2
168,169,Ethiopia,17,NaN,30,NaN,1,NaN,3,546,...,NaN,79,NaN,(.),NaN,6,NaN,LOW HUMAN DEVELOPMENT,[0.9–3.5],
169,170,Chad,17,NaN,25,NaN,1,j,44,495,...,NaN,69,NaN,..,NaN,..,NaN,LOW HUMAN DEVELOPMENT,[1.7–6.0],3.5
170,171,Central African Republic,..,NaN,..,NaN,2,NaN,69,483,...,NaN,91,NaN,..,NaN,..,NaN,LOW HUMAN DEVELOPMENT,[4.5–17.2],10.7
171,172,Mozambique,29,NaN,33,NaN,..,NaN,15,597,...,NaN,77,NaN,..,NaN,..,NaN,LOW HUMAN DEVELOPMENT,[12.5–20.0],16.1
172,173,Mali,14,NaN,30,NaN,8,NaN,38,578,...,NaN,71,NaN,..,NaN,..,NaN,LOW HUMAN DEVELOPMENT,[1.3–2.1],1.7
173,174,Niger,7,j,30,j,6,NaN,48,294,...,NaN,61,NaN,..,NaN,..,NaN,LOW HUMAN DEVELOPMENT,[0.5–1.9],1.1
174,175,Guinea-Bissau,..,NaN,..,NaN,7,NaN,58,293,...,NaN,75,NaN,..,NaN,..,NaN,LOW HUMAN DEVELOPMENT,[2.1–6.0],3.8
175,176,Burkina Faso,54,NaN,67,NaN,2,NaN,50,461,...,NaN,67,NaN,..,NaN,..,NaN,LOW HUMAN DEVELOPMENT,[1.5–2.5],2
176,177,Sierra Leone,..,NaN,..,NaN,2,NaN,61,905,...,NaN,82,NaN,..,NaN,..,NaN,LOW HUMAN DEVELOPMENT,[0.9–2.4],1.6

In [119]:
#supprimer les colonnes vides
df = df.drop(["Reference 1","Reference 2","Reference 3","Reference 4","Reference 5","Reference 6","Reference 7","Reference 8"], axis=1) 
df.head()

,HDI rank,Country,Condom use at last high-risk sex(% aged 15-24) Women 1999-2005,Condom use at last high-risk sex(% aged 15-24) Men 1999-2005,Antimalarial measures-Use of insecticide— treated bednets (% of children under five) 1999-2005,Antimalarial measures-Fevers treated with antimalarial drugs 1999-2005,"Tuberculosis cases Prevalence (per 100,000 people) 2005",Tuberculosis cases Detected under DOTS(%) 2005,Tuberculosis cases Cured under DOTS(%) 2004,Prevalence of smoking(% of adults) Women 2002-04,Prevalence of smoking(% of adults) Men 2002-04,HDI category,HIV prevalencea (% aged 15-49) 2006 range estimate,HIV prevalencea (% aged 15-49) 2006 magnitude of the estimation interval
0,1,Iceland,..,..,..,..,2,53,50,20,25,HIGH HUMAN DEVELOPMENT,[0.1–0.3],0.2
1,2,Norway,..,..,..,..,4,44,89,25,27,HIGH HUMAN DEVELOPMENT,[0.1–0.2],0.1
2,3,Australia,..,..,..,..,6,42,85,16,19,HIGH HUMAN DEVELOPMENT,[<0.2],0.1
3,4,Canada,..,..,..,..,4,64,62,17,22,HIGH HUMAN DEVELOPMENT,[0.2–0.5],0.3
4,5,Ireland,..,..,..,..,10,0,..,26,28,HIGH HUMAN DEVELOPMENT,[0.1–0.4],0.2

In [120]:
#supprimer les ".."
for c in df.columns:
    try:
        df[c] = np.where(df[c] == "..", " ", df[c])
    except TypeError:
        pass

In [121]:
df

,HDI rank,Country,Condom use at last high-risk sex(% aged 15-24) Women 1999-2005,Condom use at last high-risk sex(% aged 15-24) Men 1999-2005,Antimalarial measures-Use of insecticide— treated bednets (% of children under five) 1999-2005,Antimalarial measures-Fevers treated with antimalarial drugs 1999-2005,"Tuberculosis cases Prevalence (per 100,000 people) 2005",Tuberculosis cases Detected under DOTS(%) 2005,Tuberculosis cases Cured under DOTS(%) 2004,Prevalence of smoking(% of adults) Women 2002-04,Prevalence of smoking(% of adults) Men 2002-04,HDI category,HIV prevalencea (% aged 15-49) 2006 range estimate,HIV prevalencea (% aged 15-49) 2006 magnitude of the estimation interval
0,1,Iceland,,,,,2,53,50,20,25,HIGH HUMAN DEVELOPMENT,[0.1–0.3],0.2
1,2,Norway,,,,,4,44,89,25,27,HIGH HUMAN DEVELOPMENT,[0.1–0.2],0.1
2,3,Australia,,,,,6,42,85,16,19,HIGH HUMAN DEVELOPMENT,[<0.2],0.1
3,4,Canada,,,,,4,64,62,17,22,HIGH HUMAN DEVELOPMENT,[0.2–0.5],0.3
4,5,Ireland,,,,,10,0,,26,28,HIGH HUMAN DEVELOPMENT,[0.1–0.4],0.2
5,6,Sweden,,,,,5,56,64,18,17,HIGH HUMAN DEVELOPMENT,[0.1–0.3],0.2
6,7,Switzerland,,,,,6,0,,23,27,HIGH HUMAN DEVELOPMENT,[0.3–0.8],0.4
7,8,Japan,,,,,38,57,57,15,47,HIGH HUMAN DEVELOPMENT,[<0.2],<0.1
8,9,Netherlands,,,,,5,47,83,28,36,HIGH HUMAN DEVELOPMENT,[0.1–0.4],0.2
9,10,France,,,,,10,0,,21,30,HIGH HUMAN DEVELOPMENT,[0.3–0.8],0.4
10,11,Finland,,,,,5,0,,19,26,HIGH HUMAN DEVELOPMENT,[<0.2],0.1
11,12,United States,,,,,3,85,61,19,24,HIGH HUMAN DEVELOPMENT,[0.4–1.0],0.6
12,13,Spain,,,,,22,0,,25,39,HIGH HUMAN DEVELOPMENT,[0.4–1.0],0.6
13,14,Denmark,,,,,6,71,88,25,31,HIGH HUMAN DEVELOPMENT,[0.1–0.4],0.2
14,15,Austria,,,,,9,56,69,,,HIGH HUMAN DEVELOPMENT,[0.2–0.5],0.3
15,16,United Kingdom,,,,,11,0,,25,27,HIGH HUMAN DEVELOPMENT,[0.1–0.4],0.2
16,17,Belgium,,,,,10,64,72,25,30,HIGH HUMAN DEVELOPMENT,[0.2–0.5],0.3
17,18,Luxembourg,,,,,9,59,,26,39,HIGH HUMAN DEVELOPMENT,[0.1–0.4],0.2
18,19,New Zealand,,,,,9,51,66,22,24,HIGH HUMAN DEVELOPMENT,[<0.2],0.1
19,20,Italy,,,,,5,72,95,17,31,HIGH HUMAN DEVELOPMENT,[0.3–0.9],0.5
20,21,"Hong Kong, China (SAR)",,,,,77,55,78,4,22,HIGH HUMAN DEVELOPMENT,,
21,22,Germany,,,,,6,52,68,28,37,HIGH HUMAN DEVELOPMENT,[0.1–0.2],0.1
22,23,Israel,,,,,6,42,80,18,32,HIGH HUMAN DEVELOPMENT,[<0.2],
23,24,Greece,,,,,15,0,,29,47,HIGH HUMAN DEVELOPMENT,[0.1–0.3],0.2
24,25,Singapore,,,,,28,100,81,4,24,HIGH HUMAN DEVELOPMENT,[0.2–0.7],0.3
25,26,Korea (Republic of),,,,,135,18,80,,,HIGH HUMAN DEVELOPMENT,[<0.2],<0.1
26,27,Slovenia,,,,,15,84,90,20,28,HIGH HUMAN DEVELOPMENT,[<0.2],<0.1
27,28,Cyprus,,,,,5,57,20,,,HIGH HUMAN DEVELOPMENT,[<0.2],
28,29,Portugal,,,,,25,85,84,,,HIGH HUMAN DEVELOPMENT,[0.3–0.9],0.4
29,30,Brunei Darussalam,,,,,63,112,71,,,HIGH HUMAN DEVELOPMENT,[<0.2],<0.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147,148,Kenya,25,47,5,27,936,43,80,1,21,MEDIUM HUMAN DEVELOPMENT,[5.2–7.0],6.1
148,149,Djibouti,,,,,"1,161",42,80,,,MEDIUM HUMAN DEVELOPMENT,[0.8–6.9],3.1
149,150,Timor-Leste,,,8,19,713,44,80,,,MEDIUM HUMAN DEVELOPMENT,[<0.2],
150,151,Zimbabwe,42,69,,,631,41,54,2,20,MEDIUM HUMAN DEVELOPMENT,[13.3–27.6],20.1
151,152,Togo,22,54,54,60,753,18,67,,,MEDIUM HUMAN DEVELOPMENT,[1.9–4.7],3.2
152,153,Yemen,,,,,136,41,82,,,MEDIUM HUMAN DEVELOPMENT,[<0.2],
153,154,Uganda,53,55,0,,559,45,70,3,25,MEDIUM HUMAN DEVELOPMENT,[5.7–7.6],6.7
154,155,Gambia,,,15,55,352,69,86,,,MEDIUM HUMAN DEVELOPMENT,[1.2–4.1],2.4
155,156,Senegal,36,52,14,29,466,51,74,,,LOW HUMAN DEVELOPMENT,[0.4–1.5],0.9
156,157,Eritrea,,,4,4,515,13,85,,,LOW HUMAN DEVELOPMENT,[1.3–3.9],2.4
157,158,Nigeria,24,46,1,34,536,22,73,1,,LOW HUMAN DEVELOPMENT,[2.3–5.6],3.9
158,159,Tanzania (United Republic of),42,47,16,58,496,45,81,,,LOW HUMAN DEVELOPMENT,[5.8–7.2],6.5
159,160,Guinea,17,32,4,56,431,56,72,,,LOW HUMAN DEVELOPMENT,[1.2–1.8],1.5
160,161,Rwanda,26,40,5,13,673,29,77,,,LOW HUMAN DEVELOPMENT,[2.9–3.2],3.1
161,162,Angola,,,2,63,333,85,68,,,LOW HUMAN DEVELOPMENT,[2.3–5.3],3.7
162,163,Benin,19,34,7,60,144,83,83,,,LOW HUMAN DEVELOPMENT,[1.2–2.5],1.8
163,164,Malawi,35,47,15,28,518,39,71,5,21,LOW HUMAN DEVELOPMENT,[6.9–21.4],14.1
164,165,Zambia,35,40,7,52,618,52,83,1,16,LOW HUMAN DEVELOPMENT,[15.9–18.1],17
165,166,Côte d'Ivoire,25,56,4,58,659,38,71,,,LOW HUMAN DEVELOPMENT,[4.3–9.7],7.1
166,167,Burundi,,,1,31,602,30,78,,,LOW HUMAN DEVELOPMENT,[2.7–3.8],3.3
167,168,Congo (Democratic Republic of the),,,1,45,541,72,85,,,LOW HUMAN DEVELOPMENT,[1.8–4.9],3.2
168,169,Ethiopia,17,30,1,3,546,33,79,(.),6,LOW HUMAN DEVELOPMENT,[0.9–3.5],
169,170,Chad,17,25,1,44,495,22,69,,,LOW HUMAN DEVELOPMENT,[1.7–6.0],3.5
170,171,Central African Republic,,,2,69,483,40,91,,,LOW HUMAN DEVELOPMENT,[4.5–17.2],10.7
171,172,Mozambique,29,33,,15,597,49,77,,,LOW HUMAN DEVELOPMENT,[12.5–20.0],16.1
172,173,Mali,14,30,8,38,578,21,71,,,LOW HUMAN DEVELOPMENT,[1.3–2.1],1.7
173,174,Niger,7,30,6,48,294,50,61,,,LOW HUMAN DEVELOPMENT,[0.5–1.9],1.1
174,175,Guinea-Bissau,,,7,58,293,79,75,,,LOW HUMAN DEVELOPMENT,[2.1–6.0],3.8
175,176,Burkina Faso,54,67,2,50,461,18,67,,,LOW HUMAN DEVELOPMENT,[1.5–2.5],2
176,177,Sierra Leone,,,2,61,905,37,82,,,LOW HUMAN DEVELOPMENT,[0.9–2.4],1.6

In [123]:
destination = "HDR 2007-2008 Table 09_Source.xlsx"
df.to_csv(destination, index=False)